[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg://amtrading:amtrading@localhost:5432/amtrading

[loggers]
keys = root,sqlalchemy,alembic

[logger_root]
level = WARNING
handlers =

[logger_sqlalchemy]
level = WARNING
handlers =

[logger_alembic]
level = INFO
handlers =